version: '3'
services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ port for messaging
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

